export const PRO_MICE = [
  "Logitech G Pro X Superlight 2",
  "Logitech G Pro X Superlight",
  "Logitech G Pro Wireless",
  "Logitech G703 Lightspeed",
  "Logitech G502 X Plus",
  "Logitech G502 Hero",
  "Logitech G403 Hero",
  "Logitech G305 Lightspeed",
  "Logitech G102 Lightsync",
  "Razer DeathAdder V3 Pro",
  "Razer Viper V3 Pro",
  "Razer Viper V2 Pro",
  "Razer Viper Mini Signature Edition",
  "Razer DeathAdder V2 Pro",
  "Razer DeathAdder V2",
  "Razer Basilisk V3 Pro",
  "Razer Cobra Pro",
  "Razer Orochi V2",
  "Razer Viper Ultimate",
  "Zowie EC2-CW",
  "Zowie EC1-CW",
  "Zowie EC3-CW",
  "Zowie EC2-B",
  "Zowie EC2-C",
  "Zowie FK2-C",
  "Zowie FK1+-C",
  "Zowie S2-C",
  "Zowie S1-C",
  "Zowie ZA13-C",
  "Zowie ZA12-C",
  "Zowie ZA11-C",
  "VAXEE XE Wireless",
  "VAXEE NP-01 Wireless",
  "VAXEE NP-01S Wireless",
  "VAXEE OUTSET AX Wireless",
  "VAXEE ZYGEN NP-01",
  "Finalmouse UltralightX",
  "Finalmouse Starlight-12",
  "Finalmouse Starlight Pro - TenZ",
  "Finalmouse Air58 Ninja",
  "Finalmouse Ultralight 2",
  "Pulsar X2V2",
  "Pulsar Xlite V3",
  "Pulsar X2H",
  "Pulsar X2A",
  "Pulsar Xlite V2 Wireless",
  "Lamzu Atlantis OG V2",
  "Lamzu Maya",
  "Lamzu Thorn",
  "Lamzu Energon",
  "SteelSeries Prime Wireless",
  "SteelSeries Prime Mini Wireless",
  "SteelSeries Aerox 3 Wireless",
  "SteelSeries Aerox 5 Wireless",
  "SteelSeries Rival 3",
  "SteelSeries Rival 650",
  "HyperX Pulsefire Haste 2",
  "HyperX Pulsefire Dart",
  "G-Wolves HTS Plus 4K",
  "G-Wolves Hati-S Plus",
  "G-Wolves HSK Pro 4K",
  "Scyrox V8",
  "Ninjutso Sora V2",
  "Ninjutso Katana Superlight",
  "Ninjutso Origin One X",
  "Endgame Gear XM2we",
  "Endgame Gear OP1 8k",
  "Endgame Gear OP1we",
  "Endgame Gear XM1r",
  "Glorious Model O 2 Wireless",
  "Glorious Model D- Wireless",
  "Glorious Model I 2 Wireless",
  "Xtrfy M4 Wireless",
  "Xtrfy M42 Wireless",
  "Xtrfy MZ1 Wireless",
  "Xtrfy M8 Wireless",
  "Roccat Kone Pro Air",
  "Roccat Burst Pro",
  "Cooler Master MM711",
  "Cooler Master MM712",
  "Asus ROG Harpe Ace Aim Lab Edition",
  "Asus ROG Keris Wireless AimPoint",
  "Cherry Xtrfy M64 Pro",
  "Cherry Xtrfy M68 Pro",
  "VGN Dragonfly F1 Pro Max",
  "VXE R1 Pro",
  "Zaopin Z1 Pro"
];

export const PRO_KEYBOARDS = [
  "Wooting 60HE",
  "Wooting 80HE",
  "Wooting Two HE",
  "SteelSeries Apex Pro TKL (2023)",
  "SteelSeries Apex Pro Mini",
  "SteelSeries Apex Pro TKL Wireless",
  "SteelSeries Apex 9 TKL",
  "SteelSeries Apex 7 TKL",
  "Razer Huntsman V3 Pro TKL",
  "Razer Huntsman V3 Pro Mini",
  "Razer Huntsman V3 Pro Full Size",
  "Razer Huntsman V2 TKL",
  "Razer BlackWidow V4 Pro",
  "Razer BlackWidow V3 TKL",
  "Logitech G Pro X TKL Wireless",
  "Logitech G Pro X Keyboard",
  "Logitech G915 TKL",
  "Logitech G715",
  "Logitech G815",
  "Logitech G613",
  "Varmilo VA87M",
  "Varmilo MA87M V2",
  "Ducky One 3 TKL",
  "Ducky One 2 Mini",
  "Ducky Mecha Mini",
  "Ducky SF",
  "HyperX Alloy FPS Pro",
  "HyperX Alloy Origins Core",
  "HyperX Alloy Elite 2",
  "Corsair K70 RGB TKL",
  "Corsair K65 RGB Mini",
  "Corsair K100 RGB",
  "Corsair K70 RGB MK.2",
  "Custom Mechanical Keyboard",
  "Matrix Premium",
  "Higround Base 65",
  "Higround Basecamp 65",
  "Higround Summit 65",
  "Keychron Q1",
  "Keychron Q2",
  "Keychron K2",
  "Keychron V1",
  "Keychron K6",
  "DrunkDeer A75",
  "DrunkDeer G65",
  "Leopold FC750R",
  "Leopold FC660M",
  "Leopold FC900R",
  "Filco Majestouch 2",
  "Realforce R2 TKL",
  "Realforce GX1",
  "HHKB Professional Hybrid Type-S",
  "Anne Pro 2",
  "Akko 3068",
  "Akko Mod 007 v3",
  "GMMK Pro",
  "GMMK 2",
  "Glorious GMMK TKL",
  "ZSA Moonlander",
  "NuPhy Air75",
  "IQUNIX L80",
  "Mistel Barocco MD770"
];

export const PRO_MONITORS = [
  "Zowie XL2566K (360Hz)",
  "Zowie XL2546K (240Hz)",
  "Zowie XL2546 (240Hz)",
  "Zowie XL2540 (240Hz)",
  "Zowie XL2746K (240Hz)",
  "Zowie XL2546S (240Hz)",
  "Zowie XL2586X (540Hz)",
  "Zowie XL2546X (240Hz)",
  "Zowie XL2540K (240Hz)",
  "Zowie XL2411K (144Hz)",
  "ASUS ROG Swift PG259QN (360Hz)",
  "ASUS ROG Swift PG27AQN (360Hz)",
  "ASUS ROG Swift PG258Q (240Hz)",
  "ASUS ROG Swift Pro PG248QP (540Hz)",
  "ASUS ROG Swift PG27AQDM (240Hz OLED)",
  "ASUS ROG Swift PG259QNR (360Hz)",
  "ASUS TUF Gaming VG259QM (280Hz)",
  "ASUS TUF Gaming VG249Q (144Hz)",
  "ASUS VG248QE (144Hz)",
  "Alienware AW2521H (360Hz)",
  "Alienware AW2523HF (360Hz)",
  "Alienware AW2518H (240Hz)",
  "Alienware AW2524H (500Hz)",
  "Alienware AW2723DF (280Hz)",
  "LG UltraGear 27GR95QE (240Hz OLED)",
  "LG UltraGear 27GN750 (240Hz)",
  "LG UltraGear 24GN600 (144Hz)",
  "LG UltraGear 27GP850 (165Hz)",
  "Samsung Odyssey G7 (240Hz)",
  "Samsung Odyssey G9 (240Hz)",
  "Samsung Odyssey G6 (240Hz)",
  "Samsung Odyssey G4 (240Hz)",
  "MSI G251FG (360Hz)",
  "MSI Optix MAG251RX (240Hz)",
  "MSI MAG 271QPX (240Hz OLED)",
  "Acer Predator X25 (360Hz)",
  "Acer Nitro XV252Q F (390Hz)",
  "ViewSonic XG2431 (240Hz)",
  "ViewSonic XG251G (360Hz)",
  "AOC 24G2 (144Hz)",
  "AOC AGON AG251FZ (240Hz)",
  "AOC C24G1 (144Hz)",
  "HP Omen X 25 (240Hz)",
  "Gigabyte M27Q (170Hz)",
  "Gigabyte G24F (165Hz)"
];

export const PRO_MOUSEPADS = [
  "Artisan Zero (Soft)",
  "Artisan Ninja FX Zero Soft Black",
  "Artisan Zero (XSoft)",
  "Artisan Zero (Mid)",
  "Artisan Hayate Otsu (Soft)",
  "Artisan Hayate Otsu (XSoft)",
  "Artisan Hayate Otsu (Mid)",
  "Artisan Hien (Soft)",
  "Artisan Hien (Mid)",
  "Artisan Hien (XSoft)",
  "Artisan Raiden (XSoft)",
  "Artisan Raiden (Mid)",
  "Artisan Shidenkai V2",
  "Artisan Kou (Soft)",
  "SteelSeries Qck Heavy",
  "SteelSeries Qck+",
  "SteelSeries Qck Edge",
  "SteelSeries Qck Mass",
  "SteelSeries Qck Prism",
  "Zowie G-SR-SE (Gris/Rouge)",
  "Zowie G-SR-SE (Deep Blue)",
  "Zowie G-SR-SE (Bi)",
  "Zowie G-SR-SE (Tyloo)",
  "Zowie G-SR-SE (Pink/Divina)",
  "Zowie G-SR II",
  "Zowie G-SR (Black)",
  "Zowie P-SR",
  "Logitech G640",
  "Logitech G840",
  "Logitech G740",
  "Logitech G240",
  "Logitech G440 (Hard)",
  "Razer Gigantus V2",
  "Razer Strider",
  "Razer Goliathus Speed",
  "Razer Goliathus Control",
  "Razer Firefly V2",
  "VAXEE PA",
  "VAXEE PB",
  "Lethal Gaming Gear Saturn Pro",
  "Lethal Gaming Gear Venus Pro",
  "Lethal Gaming Gear Saturn",
  "Lethal Gaming Gear Venus",
  "Lethal Gaming Gear Jupiter",
  "SkyPAD Glass 3.0",
  "Wallhack SP-004",
  "Wallhack MO-001",
  "BenQ Zowie G-SR",
  "HyperX Fury S Pro",
  "HyperX Fury S Speed",
  "Xtrfy GP4",
  "Xtrfy GP1",
  "Xtrfy GP2",
  "Fnatic Dash",
  "Fnatic Focus 3",
  "Fnatic Jet",
  "Gamesense Radar",
  "Aqua Control 2",
  "Aqua Control+",
  "Aqua Control 2 (Sakura)",
  "X-raypad Equate Plus",
  "The Mousepad Company Strata",
  "Odin Gaming ZeroGravity",
  "Pulsar ES2",
  "Pulsar ES1",
  "Pulsar Paraspeed",
  "Pulsar Superglide (Glass)",
  "PureTrak Talent",
  "Glorious Fire",
  "Glorious Ice",
  "Corsair MM300",
  "Corsair MM350",
  "Cooler Master MP511"
];
