export const PRO_MICE = [
  "Logitech G Pro X Superlight 2",
  "Logitech G Pro X Superlight",
  "Logitech G Pro Wireless",
  "Logitech G703 Lightspeed",
  "Logitech G502 X Plus",
  "Logitech G502 Hero",
  "Logitech G403 Hero",
  "Logitech G305 Lightspeed",
  "Logitech G102 Lightsync",
  "Razer DeathAdder V3 Pro",
  "Razer Viper V3 Pro",
  "Razer Viper V2 Pro",
  "Razer Viper Mini Signature Edition",
  "Razer DeathAdder V2 Pro",
  "Razer DeathAdder V2",
  "Razer Basilisk V3 Pro",
  "Razer Cobra Pro",
  "Razer Orochi V2",
  "Razer Viper Ultimate",
  "Zowie EC2-CW",
  "Zowie EC1-CW",
  "Zowie EC3-CW",
  "Zowie EC2-B",
  "Zowie EC2-C",
  "Zowie FK2-C",
  "Zowie FK1+-C",
  "Zowie S2-C",
  "Zowie S1-C",
  "Zowie ZA13-C",
  "Zowie ZA12-C",
  "Zowie ZA11-C",
  "VAXEE XE Wireless",
  "VAXEE NP-01 Wireless",
  "VAXEE NP-01S Wireless",
  "VAXEE OUTSET AX Wireless",
  "VAXEE ZYGEN NP-01",
  "Finalmouse UltralightX",
  "Finalmouse Starlight-12",
  "Finalmouse Starlight Pro - TenZ",
  "Finalmouse Air58 Ninja",
  "Finalmouse Ultralight 2",
  "Pulsar X2V2",
  "Pulsar Xlite V3",
  "Pulsar X2H",
  "Pulsar X2A",
  "Pulsar Xlite V2 Wireless",
  "Lamzu Atlantis OG V2",
  "Lamzu Maya",
  "Lamzu Thorn",
  "Lamzu Energon",
  "SteelSeries Prime Wireless",
  "SteelSeries Prime Mini Wireless",
  "SteelSeries Aerox 3 Wireless",
  "SteelSeries Aerox 5 Wireless",
  "SteelSeries Rival 3",
  "SteelSeries Rival 650",
  "HyperX Pulsefire Haste 2",
  "HyperX Pulsefire Dart",
  "G-Wolves HTS Plus 4K",
  "G-Wolves Hati-S Plus",
  "G-Wolves HSK Pro 4K",
  "Scyrox V8",
  "Ninjutso Sora V2",
  "Ninjutso Katana Superlight",
  "Ninjutso Origin One X",
  "Endgame Gear XM2we",
  "Endgame Gear OP1 8k",
  "Endgame Gear OP1we",
  "Endgame Gear XM1r",
  "Glorious Model O 2 Wireless",
  "Glorious Model D- Wireless",
  "Glorious Model I 2 Wireless",
  "Xtrfy M4 Wireless",
  "Xtrfy M42 Wireless",
  "Xtrfy MZ1 Wireless",
  "Xtrfy M8 Wireless",
  "Roccat Kone Pro Air",
  "Roccat Burst Pro",
  "Cooler Master MM711",
  "Cooler Master MM712",
  "Asus ROG Harpe Ace Aim Lab Edition",
  "Asus ROG Keris Wireless AimPoint",
  "Cherry Xtrfy M64 Pro",
  "Cherry Xtrfy M68 Pro",
  "VGN Dragonfly F1 Pro Max",
  "VXE R1 Pro",
  "Zaopin Z1 Pro",
  "BenQ Zowie FK1-B",
  "BenQ Zowie S2 Divina",
  "TRUST GXT 179 Gamers",
  "SteelSeries Rival 5",
  "SteelSeries Rival 600",
  "SteelSeries Sensei Ten",
  "Corsair Dark Core RGB Pro",
  "Corsair M65 RGB Ultra",
  "Corsair Ironclaw RGB",
  "Mad Catz R.A.T. 8+ Pro",
  "Mad Catz R.A.T. Pro X",
  "Turtle Beach Krait Ultra",
  "Gigabyte Aorus M5",
  "MSI Clutch GM11",
  "Turtle Beach Krait",
  "Kingston Fury Beast Pro",
  "Patriot Viper V560",
  // 추가: DB 프로게이머 사용 장비
  "ZOWIE FK2-DW Black",
  "ZOWIE EC2-DW Black",
  "ZOWIE EC2-DW Glossy",
  "ZOWIE EC2-DW Grey",
  "ZOWIE EC3-DW Black",
  "ZOWIE EC3-DW Glossy",
  "ZOWIE U2-DW Black",
  "ZOWIE FK1-C",
  "ZOWIE x donk Mouse",
  "Finalmouse Ultralight X Medium",
  "Finalmouse Ultralight X Large",
  "Finalmouse Ultralight X Prophecy ScreaM Classic",
  "Finalmouse Ultralight X Prophecy Clix Small",
  "HITSCAN Hyperlight Black",
  "Pulsar X2 V2 Black",
  "Pulsar X2N",
  "Pulsar X2N Crazylight Medium",
  "Pulsar Xlite V4 Es Medium",
  "Pulsar eS FS-1",
  "Pulsar ZywOo The Chosen Mouse Black",
  "Pulsar ZywOo The Chosen Mouse White",
  "Pulsar TenZ Signature Edition",
  "PULSAR TENZ EDITION",
  "Pulsar Susanto-X",
  "Logitech G303 Shroud Edition",
  "Logitech G903",
  "Logitech G Pro X2 SUPERSTRIKE",
  "Logitech G Pro 2 LIGHTSPEED Magenta",
  "G-Wolves Hati S+ 4K",
  "G-Wolves Hati S+ 8K",
  "Razer Viper V4 Pro",
  "Razer Viper V4 Pro Black",
  "Razer Viper V3 Hyperspeed",
  "Razer DeathAdder V3 HyperSpeed",
  "Razer DeathAdder V4 Pro Black",
  "Razer DeathAdder V4 Pro White",
  "Razer DeathAdder V4 Pro Green",
  "Razer DeathAdder V4 Pro NiKo Edition",
  "Razer Basilisk Ultimate",
  "SONY INZONE Mouse-A",
  "VGN Dragonfly MOBA",
  "Alienware Pro Wireless Gaming Mouse",
  "Lamzu Atlantis Mini",
  "Endgame Gear OP1w 4K Black",
  "ROCCAT Kain 200 Aimo",
  "WLMouse Beast X Max Red",
  "WLMouse BEAST X Silver",
  "Fallen Gear Lobo Wireless",
  "Corsair Sabre v2 Pro",
  "VAXEE XE V2 White",
  "VAXEE XE V2 Black",
  "VAXEE XE V2 Pink",
  "VAXEE XE V2 Fluorescent Green",
  "VAXEE E1 Wireless White",
  "VAXEE E1 Wireless Red",
  "Cooler Master MM710",
  "ATK Blazing Sky F1",
  "ATK Dragonfly A9",
  "ASUS ROG Harpe Ace 2 Black",
  "Corsair Katar Pro Wireless"
];

export const PRO_KEYBOARDS = [
  "Wooting 60HE",
  "Wooting 80HE",
  "Wooting Two HE",
  "SteelSeries Apex Pro TKL (2023)",
  "SteelSeries Apex Pro Mini",
  "SteelSeries Apex Pro TKL Wireless",
  "SteelSeries Apex 9 TKL",
  "SteelSeries Apex 7 TKL",
  "Razer Huntsman V3 Pro TKL",
  "Razer Huntsman V3 Pro Mini",
  "Razer Huntsman V3 Pro Full Size",
  "Razer Huntsman V2 TKL",
  "Razer BlackWidow V4 Pro",
  "Razer BlackWidow V3 TKL",
  "Logitech G Pro X TKL Wireless",
  "Logitech G Pro X Keyboard",
  "Logitech G915 TKL",
  "Logitech G715",
  "Logitech G815",
  "Logitech G613",
  "Varmilo VA87M",
  "Varmilo MA87M V2",
  "Ducky One 3 TKL",
  "Ducky One 2 Mini",
  "Ducky Mecha Mini",
  "Ducky SF",
  "HyperX Alloy FPS Pro",
  "HyperX Alloy Origins Core",
  "HyperX Alloy Elite 2",
  "Corsair K70 RGB TKL",
  "Corsair K65 RGB Mini",
  "Corsair K100 RGB",
  "Corsair K70 RGB MK.2",
  "Custom Mechanical Keyboard",
  "Matrix Premium",
  "Higround Base 65",
  "Higround Basecamp 65",
  "Higround Summit 65",
  "Keychron Q1",
  "Keychron Q2",
  "Keychron K2",
  "Keychron V1",
  "Keychron K6",
  "DrunkDeer A75",
  "DrunkDeer G65",
  "Leopold FC750R",
  "Leopold FC660M",
  "Leopold FC900R",
  "Filco Majestouch 2",
  "Realforce R2 TKL",
  "Realforce GX1",
  "HHKB Professional Hybrid Type-S",
  "Anne Pro 2",
  "Akko 3068",
  "Akko Mod 007 v3",
  "GMMK Pro",
  "GMMK 2",
  "Glorious GMMK TKL",
  "ZSA Moonlander",
  "NuPhy Air75",
  "IQUNIX L80",
  "Mistel Barocco MD770",
  "Monsgeek King Kong 87",
  "Epomaker GK96S",
  "Ajazz AK820",
  "Gateron Apex Pro",
  "Corsair K70 Lux",
  "Steelseries Apex M800",
  "Razer Huntsman Elite",
  "Razer Pro Type Ultra",
  "GMMK 2 Pro",
  "Keychron K8 Pro",
  "iKBC CD108",
  "Novelkeys NK87 Entry",
  "Input Club K-Type",
  // 추가: DB 프로게이머 사용 장비
  "Meletrix BOOG75",
  "Razer BlackWidow V3 Pro",
  "Razer BlackWidow V3 Mini",
  "Razer BlackWidow V4 75%",
  "Razer Huntsman Mini",
  "Razer Huntsman TE",
  "Razer Blackwidow Chroma TE V2",
  "Higround Performance Base 65",
  "Durgod Taurus K320",
  "HyperX Alloy Origins 60",
  "ASUS ROG Falchion RX Low Profile",
  "ASUS ROG Falchion Ace HFX Black",
  "ASUS ROG Falchion Ace HFX ZywOo Edition",
  "ASUS ROG Falchion Ace 75 HE White",
  "ASUS ROG Falchion Ace 75 HE Black",
  "ASUS ROG Falcata",
  "Logitech G Pro Keyboard",
  "Logitech G Pro Mechanical Gaming Keyboard",
  "Logitech G Pro X TKL Keyboard",
  "Logitech G Pro X TKL RAPID",
  "Logitech G Pro X TKL RAPID Black",
  "Logitech G Pro X TKL RAPID White",
  "Logitech G Pro X 60 Black",
  "Logitech G512",
  "Logitech G610",
  "Logitech G713",
  "Logitech G913 TKL",
  "ROCCAT Vulcan TKL Pro",
  "Corsair K70 PRO TKL Black",
  "SteelSeries Apex Pro TKL Gen 3 White",
  "SteelSeries Apex Pro TKL Gen 3 Black",
  "Pulsar PCMK 2 HE TKL White",
  "Pulsar PCMK 3",
  "Fnatic miniSTREAK",
  "Sony INZONE KBD-H75",
  "ZENAIM Keyboard",
  "ATK RS6 Ultra Aspas Edition",
  "Wooting 60 HE",
  "Logitech G Pro X Mechanical Keyboard",
  "Logitech G Pro Mechanical Keyboard",
  "Logitech G Pro X Mechanical Gaming Keyboard"
];

export const PRO_MONITORS = [
  "Zowie XL2566K (360Hz)",
  "Zowie XL2546K (240Hz)",
  "Zowie XL2546 (240Hz)",
  "Zowie XL2540 (240Hz)",
  "Zowie XL2746K (240Hz)",
  "Zowie XL2546S (240Hz)",
  "Zowie XL2586X (540Hz)",
  "Zowie XL2546X (240Hz)",
  "Zowie XL2540K (240Hz)",
  "Zowie XL2411K (144Hz)",
  "ASUS ROG Swift PG259QN (360Hz)",
  "ASUS ROG Swift PG27AQN (360Hz)",
  "ASUS ROG Swift PG258Q (240Hz)",
  "ASUS ROG Swift Pro PG248QP (540Hz)",
  "ASUS ROG Swift PG27AQDM (240Hz OLED)",
  "ASUS ROG Swift PG259QNR (360Hz)",
  "ASUS TUF Gaming VG259QM (280Hz)",
  "ASUS TUF Gaming VG249Q (144Hz)",
  "ASUS VG248QE (144Hz)",
  "Alienware AW2521H (360Hz)",
  "Alienware AW2523HF (360Hz)",
  "Alienware AW2518H (240Hz)",
  "Alienware AW2524H (500Hz)",
  "Alienware AW2723DF (280Hz)",
  "LG UltraGear 27GR95QE (240Hz OLED)",
  "LG UltraGear 27GN750 (240Hz)",
  "LG UltraGear 24GN600 (144Hz)",
  "LG UltraGear 27GP850 (165Hz)",
  "Samsung Odyssey G7 (240Hz)",
  "Samsung Odyssey G9 (240Hz)",
  "Samsung Odyssey G6 (240Hz)",
  "Samsung Odyssey G4 (240Hz)",
  "MSI G251FG (360Hz)",
  "MSI Optix MAG251RX (240Hz)",
  "MSI MAG 271QPX (240Hz OLED)",
  "Acer Predator X25 (360Hz)",
  "Acer Nitro XV252Q F (390Hz)",
  "ViewSonic XG2431 (240Hz)",
  "ViewSonic XG251G (360Hz)",
  "AOC 24G2 (144Hz)",
  "AOC AGON AG251FZ (240Hz)",
  "AOC C24G1 (144Hz)",
  "HP Omen X 25 (240Hz)",
  "Gigabyte M27Q (170Hz)",
  "Gigabyte G24F (165Hz)",
  // 추가: DB 프로게이머 사용 장비
  "ZOWIE XL2566X+",
  "ZOWIE XL2586X+",
  "BenQ ZOWIE XL2566K",
  "BenQ ZOWIE XL2546K",
  "BenQ ZOWIE XL2546",
  "SONY INZONE M10S",
  "AOC C27G2ZE",
  "LG ULTRAGEAR 27GN950-B",
  "LG ULTRAGEAR 32GQ950-B",
  "LG ULTRAGEAR 27GN750-B",
  "MSI Optix G271",
  "Dell S2522HG",
  "ASUS TUF VG259QM",
  "ASUS TUF VG258QM",
  "ASUS ROG XG258Q",
  "ASUS ROG STRIX XG248Q",
  "Acer Predator XB252Q",
  "Acer Predator XB272",
  "Alienware AW2721D",
  "Alienware AW2521HF",
  "Alienware AW3225QF",
  "Samsung C24RG54FQU",
  "HP OMEN 27i",
  "HP OMEN 24.5",
  "OMEN 25i",
  "OMEN 25",
  "OMEN by HP 25"
];

export const PRO_MOUSEPADS = [
  "Artisan Zero (Soft)",
  "Artisan Ninja FX Zero Soft Black",
  "Artisan Zero (XSoft)",
  "Artisan Zero (Mid)",
  "Artisan Hayate Otsu (Soft)",
  "Artisan Hayate Otsu (XSoft)",
  "Artisan Hayate Otsu (Mid)",
  "Artisan Hien (Soft)",
  "Artisan Hien (Mid)",
  "Artisan Hien (XSoft)",
  "Artisan Raiden (XSoft)",
  "Artisan Raiden (Mid)",
  "Artisan Shidenkai V2",
  "Artisan Kou (Soft)",
  "SteelSeries Qck Heavy",
  "SteelSeries Qck+",
  "SteelSeries Qck Edge",
  "SteelSeries Qck Mass",
  "SteelSeries Qck Prism",
  "Zowie G-SR-SE (Gris/Rouge)",
  "Zowie G-SR-SE (Deep Blue)",
  "Zowie G-SR-SE (Bi)",
  "Zowie G-SR-SE (Tyloo)",
  "Zowie G-SR-SE (Pink/Divina)",
  "Zowie G-SR II",
  "Zowie G-SR (Black)",
  "Zowie P-SR",
  "Logitech G640",
  "Logitech G840",
  "Logitech G740",
  "Logitech G240",
  "Logitech G440 (Hard)",
  "Razer Gigantus V2",
  "Razer Strider",
  "Razer Goliathus Speed",
  "Razer Goliathus Control",
  "Razer Firefly V2",
  "VAXEE PA",
  "VAXEE PB",
  "Lethal Gaming Gear Saturn Pro",
  "Lethal Gaming Gear Venus Pro",
  "Lethal Gaming Gear Saturn",
  "Lethal Gaming Gear Venus",
  "Lethal Gaming Gear Jupiter",
  "SkyPAD Glass 3.0",
  "Wallhack SP-004",
  "Wallhack MO-001",
  "BenQ Zowie G-SR",
  "HyperX Fury S Pro",
  "HyperX Fury S Speed",
  "Xtrfy GP4",
  "Xtrfy GP1",
  "Xtrfy GP2",
  "Fnatic Dash",
  "Fnatic Focus 3",
  "Fnatic Jet",
  "Gamesense Radar",
  "Aqua Control 2",
  "Aqua Control+",
  "Aqua Control 2 (Sakura)",
  "X-raypad Equate Plus",
  "The Mousepad Company Strata",
  "Odin Gaming ZeroGravity",
  "Pulsar ES2",
  "Pulsar ES1",
  "Pulsar Paraspeed",
  "Pulsar Superglide (Glass)",
  "PureTrak Talent",
  "Glorious Fire",
  "Glorious Ice",
  "Corsair MM300",
  "Corsair MM350",
  "Cooler Master MP511",
  "Endgame Gear OP1 8K",
  "Razer Strider Pro",
  "Cooler Master MP511 XL",
  "Ducky Sherlock Dark",
  "Ducky Sherlock Frost",
  "Logitech G Pro X",
  "SteelSeries QcK Large",
  "SteelSeries QcK XL",
  "SteelSeries QcK Performance Speed",
  "HyperX Fury L Pro",
  "Corsair MM800",
  "Corsair MM500",
  "Turtle Beach Flash Pro",
  "Vanguard VG Infinity",
  "Glorious 3XL Extended",
  "Razer Invicta",
  "Mad Catz Glide 38",
  "Kingston Fury Beast XL",
  "Patriot Viper V1 Pro",
  // 추가: DB 프로게이머 사용 장비
  "Artisan Ninja FX Zero Soft Orange",
  "Artisan Ninja FX Zero XSoft Black",
  "Artisan Ninja FX Zero XSoft Orange",
  "Artisan Ninja FX Zero XSoft",
  "Artisan Ninja FX Zero Mid",
  "Artisan Ninja FX Zero Mid Orange",
  "Artisan Ninja FX Shidenkai XSoft Black",
  "Artisan Hayate Otsu Soft Black",
  "Artisan Hayate Otsu Soft Wine Red",
  "Artisan Hayate Otsu XSoft Black",
  "Artisan Hayate Otsu Mid Wine Red",
  "Artisan FX Hien Soft Black",
  "Artisan FX Hien XSoft Wine Red",
  "Artisan Raiden FX Mid",
  "Artisan Raiden FX XSoft",
  "Artisan Raiden FX Soft Coffee Brown",
  "Artisan Key-83 XSoft",
  "Artisan Type-99 Soft Black",
  "Artisan Type-99 XSoft Black",
  "Artisan Type-99 Gray",
  "Artisan Type-99 Matcha",
  "SkyPAD 3.0",
  "SkyPAD 3.0 XL",
  "ZOWIE G-SR-SE Rouge",
  "ZOWIE G-SR-SE ROUGE II",
  "ZOWIE G-SR-SE Blue",
  "ZOWIE G-SR-SE BLUE II",
  "ZOWIE G-SR-SE Bi",
  "ZOWIE G-SR-SE Bi II",
  "ZOWIE G-SR-SE Divina Blue",
  "ZOWIE G-SR-SE Gris",
  "ZOWIE G-TR",
  "ZOWIE H-SR III",
  "ZOWIE H-SR-SE BLUE II",
  "Pulsar x LGG Saturn Pro Black",
  "Pulsar x LGG Venus Pro Red",
  "Pulsar x LGG Jupiter Pro",
  "Pulsar eS Saturn Pro Black",
  "Pulsar eS Saturn Pro Red",
  "Xraypad Aqua Control II Black",
  "Higround Performance Mousepad",
  "Yuki Aim Oni Black",
  "Yuki Aim x Demon1 Cloth",
  "InfinityMice Infinite Speed Matcha Green",
  "Fallen Gear Mystic",
  "Fnatic FOCUS 2",
  "Fnatic FOCUS3 MAX",
  "Abyss Gaming Scarlet",
  "Roccat Sense AIMO",
  "A4Tech X7-500MP",
  "CHERRY XTRFY GP7",
  "Degster Victorious Dawn",
  "Odin Gaming Andromeda Pro",
  "BanKs Collection Heavy Claw by ESPTIGER",
  "VAXEE PD150",
  "VAXEE PD151",
  "VAXEE PE Kumo",
  "VAXEE PE-K Pink",
  "SONY INZONE MAT-D",
  "La Onda QCW Molten Edge",
  "The Chosen Mousepad",
  "Mionix Sargas",
  "Artisan Ninja FX Zero (Soft)"
];

// ── Country flag helpers ──────────────────────────────────────────────────────

/** Player name → ISO 3166-1 alpha-2 country code */
export const PLAYER_NATIONALITIES: Record<string, string> = {
  // ── Valorant ──────────────────────────────────────────────────────────────
  Alfajer: 'TR', ANGE1: 'UA', aspas: 'BR', Asuna: 'US', autimatic: 'US',
  babybay: 'US', bang: 'KR', benjyfishy: 'GB', BeYN: 'KR', Blowz: 'CL',
  Boaster: 'GB', Boo: 'US', Boostio: 'US', brawk: 'US', BuZz: 'KR',
  cauanzin: 'BR', CB: 'CN', cgrs: 'SG', CHICHOO: 'TR', Chronicle: 'RU',
  cortezia: 'US', crashies: 'US', Cryocells: 'US',
  d4v41: 'SG', Dantedeu5: 'AR', Demon1: 'RU', Derke: 'FI', derrek: 'US', dos9: 'FR',
  eeiu: 'US', Ethan: 'US',
  f0rsakeN: 'SG', Flicker: 'KR', Foxy9: 'KR', free1ng: 'KR', frttt: 'SE',
  Haodong: 'CN', HYUNMIN: 'KR',
  iZu: 'KR', Invy: 'SG',
  Jamppi: 'FI', jawgemo: 'US', Jinggg: 'SG', johnqt: 'TN', JonahP: 'US',
  kaajak: 'DK', kamo: 'JP', Karon: 'BR', Keiko: 'US', keznit: 'CL',
  kiNgg: 'AU', Knight: 'CN', Koshmaras: 'RU', Kyu: 'KR',
  Lakia: 'KR', Laz: 'JP', leaf: 'US', Leo: 'SE', Less: 'BR', Levius: 'CN',
  Lewn: 'FR', Lothar: 'KR', Lukxo: 'BR',
  Magnum: 'US', MaKo: 'KR', Mazino: 'KR', Mendo: 'US', Meteor: 'KR',
  mimi: 'DE', mindfreak: 'AU', MiniBoo: 'KR', Moose: 'US', Munchkin: 'KR',
  mwzera: 'BR',
  N4RRATE: 'US', nAts: 'RU', NaturE: 'KR', Neon: 'PH', nephh: 'CN',
  nitr0: 'US', Nivera: 'FR',
  OXY: 'US',
  pANcada: 'BR', PROD: 'SE', primmie: 'US', purp0: 'SE',
  reduxx: 'US', RieNs: 'KR', rushia: 'CN', runi: 'US',
  s0m: 'US', Saadhak: 'AR', Sacy: 'BR', Sato: 'JP', Sayf: 'SE',
  ScreaM: 'BE', ShahZaM: 'US', Shanks: 'AU', Shao: 'RU', Sheydos: 'RU',
  silentzz: 'AR', SirMaza: 'KR', skuba: 'CA', Skairipa: 'BR', Smoggy: 'US',
  sociablEE: 'TR', something: 'US', spikeziN: 'US', sScary: 'US', stax: 'KR',
  SugarZ3ro: 'JP', supamen: 'KR', Suygetsu: 'RU', SyouTa: 'JP',
  t3xture: 'US', tarik: 'US', TenZ: 'CA', timotino: 'US', trent: 'US',
  tteuw: 'BR', tuyz: 'BR',
  valyn: 'US', vanity: 'US', Verno: 'BR', Virtyy: 'BR',
  Wayne: 'CN', whzy: 'CN', Wo0t: 'US',
  xccurate: 'ID', Xdll: 'JP', Xeppaa: 'US', xeus: 'TR',
  yay: 'US', yetujey: 'TR',
  zekken: 'US', Zellsis: 'US', ZmjjKK: 'CN', ZynX: 'KR',
  AAAAY: 'CN', Abo: 'CN', BerLIN: 'DE',

  // ── CS2 ───────────────────────────────────────────────────────────────────
  '910': 'CN',
  Aleksib: 'FI', ALEX: 'GB', apEX: 'FR', Ax1Le: 'RU',
  b1t: 'UA', blameF: 'DK', bLitz: 'US', bodyy: 'FR', Boombl4: 'RU',
  brnz4n: 'BR', broky: 'LV', Brollan: 'SE', buda: 'AR',
  cadiaN: 'DK', Calyx: 'TR', chelo: 'BR', chopper: 'RU',
  degster: 'RU', dev1ce: 'DK', device: 'DK', donk: 'RU', drop: 'BR',
  EliGE: 'US', electroNic: 'UA', exit: 'BR',
  FalleN: 'BR', fame: 'RU', Finn: 'SE', flameZ: 'IL', floppy: 'US', frozen: 'SK',
  gla1ve: 'DK', Grim: 'US',
  hades: 'UA', hallzerk: 'NO', hampus: 'SE', huNter: 'BA',
  iM: 'UA', insani: 'BR', interz: 'RU', isak: 'SE',
  jabbi: 'DK', Jame: 'KZ', JDC: 'US', Jimpphat: 'FI', jks: 'AU', jL: 'UA', JT: 'US',
  karrigan: 'DK', knife: 'RU', Krimbo: 'DE', KRIMZ: 'SE', kscerato: 'BR', kyousuke: 'BR', kyxsan: 'SE',
  m0NESY: 'FR', maden: 'TR', Magisk: 'DK', magixx: 'RU', MAJ3R: 'TR',
  malbsMd: 'US', MartinezSa: 'ES', matys: 'FR', maxster: 'SE', mezii: 'GB', mzinho: 'MN',
  NAF: 'CA', nawwk: 'SE', NEOFRAG: 'MK', Nertz: 'UA', NiKo: 'BA',
  r1nkle: 'US', rain: 'NO', reedz: 'SE', REZ: 'SE', ropz: 'EE',
  s1mple: 'UA', saffee: 'BR', Senzu: 'MN', sh1ro: 'RU', siuhy: 'DK',
  sjuush: 'DK', skullz: 'BR', Snappi: 'DK', Snax: 'PL', Spinx: 'IL',
  Staehr: 'DK', stavn: 'DK', SunPayus: 'TR', syrsoN: 'RU',
  tabseN: 'DE', Techno4K: 'MN', TeSeS: 'DK', torzsi: 'HU', Twistzz: 'CA',
  tyler: 'US',
  ultimate: 'CN',
  w0nderful: 'CN', Wicadia: 'PL', woxic: 'TR',
  XANTARES: 'TR', xertioN: 'DE', Xyp9x: 'DK',
  YEKINDAR: 'LV', yuurih: 'BR',
  Zerb: 'MN', zont1x: 'RU', ZywOo: 'FR',
  // extra CS2
  acoR: 'DK', arT: 'BR', biguzera: 'BR', buster: 'MN', coldzera: 'BR',
  dumau: 'BR', dupreeh: 'DK', es3tag: 'DK', Ex3rcice: 'FR', fer: 'BR', felps: 'BR',
  FL1T: 'RU', HUASOPEEK: 'CL',
  k0nfig: 'DK', Krad: 'RU', KSCERATO: 'BR', kauez: 'BR',
  latto: 'BR', nexa: 'RS',
  nqz: 'BR', npl: 'UA', oSee: 'US',
  Plopski: 'SE', Qikert: 'KZ', reix: 'BR',
  sl3nd: 'NO', snow: 'BR',
  TMB: 'SK', tN: 'DK', trk: 'BR', twistzz: 'CA',
  volt: 'FI', vsm: 'BR', woro2k: 'ES', Nertzy: 'UA',

  // ── Overwatch 2 ───────────────────────────────────────────────────────────
  AimGod: 'KR', AlphaYi: 'KR', birdring: 'KR', Carpe: 'KR', Checkmate: 'KR',
  ChiYo: 'JP', Chorong: 'KR', Crimzo: 'US', Donghun: 'KR', Fearless: 'KR',
  Fielder: 'KR', Fleta: 'KR', FunnyAstro: 'US', Glister: 'KR', Guxue: 'CN',
  Hadi: 'SA', HanBin: 'KR', Harbleu: 'US', Heesu: 'KR', HeeSang: 'KR',
  Hybrid: 'GB', Hydron: 'US', infekted: 'SE', IR1S: 'FR',
  Izayaki: 'US', JinMu: 'CN', JJoNaK: 'KR', Junbin: 'KR',
  kevster: 'SE', Ksaa: 'SA', Landon: 'US', Lastro: 'KR', LBBD7: 'KR',
  LeeJaeGon: 'KR', Lengsa: 'CN', Lethal: 'US', LIP: 'KR', Lyar: 'KR',
  Mag: 'KR', Masaa: 'DE', Mer1t: 'KR', Mmonk: 'KR', MuZe: 'FR',
  nero: 'US', Patiphan: 'TH', Pelican: 'KR', Piggy: 'KR', Profit: 'KR',
  Prophet: 'US', proud: 'KR', Quartz: 'US', rakattack: 'US', Rawkus: 'US',
  Rupal: 'IN', sauceror: 'US', Sayaplayer: 'KR', seeker: 'KR', Shax: 'FR',
  Shu: 'US', Shy: 'KR', SirMajed: 'SA', skewed: 'US', Someone: 'KR',
  SoOn: 'FR', SP9RK1E: 'KR', SparkR: 'KR', Stalk3r: 'KR', sugarfree: 'US',
  ta1yo: 'US', UV: 'KR', Vega: 'KR', Vigilante: 'US', Viol2t: 'US',
  Viper: 'KR', Void: 'KR', XepheR: 'FR', Xzi: 'KR', Xzite: 'US',
  Yaki: 'KR', Youbi: 'KR', Zest: 'KR',
  // shared name (OW2 Backbone = different from other games)

  // ── Apex Legends ──────────────────────────────────────────────────────────
  '9impulse': 'US', aceu: 'US', Akku: 'SE', Albralelie: 'US', Apryze: 'US',
  ChaoticMuch: 'US', chocoTaco: 'US', Crust: 'US', Crylix: 'CA', Daltoosh: 'US',
  Dezignful: 'US', Diegosaurs: 'MX', Dizzy: 'US', dooplex: 'US', Dropped: 'US',
  Effect: 'TR', Enemy: 'US', esdesu: 'JP', Faide: 'SE', Ftyan: 'TR',
  Genburten: 'NL', Gnaske: 'SE', Hakis: 'SE', HAL: 'US', Hardecki: 'PL',
  Hiarka: 'DE', HisWattson: 'US', iiTzTimmy: 'US', ImMikeyyyz: 'US', ImperialHal: 'US',
  KaronPe: 'BR', Keon: 'US', Koyful: 'SE', Leamonhead: 'US', LiNkzr: 'SE',
  Lou: 'US', lyr1c: 'US', Mande: 'DE', MaTaFe: 'BR', Monsoon: 'US',
  Neazul: 'SE', Nickmercs: 'US', Nocturnal: 'US', Noko: 'KR', ojrein: 'US',
  oraxe: 'BR', ParkHa: 'KR', Phony: 'US', Prycyy: 'SE', psalm: 'US',
  Ras: 'US', Reps: 'FI', Rogue: 'US', Roieee: 'US', rpr: 'JP',
  Satuki: 'JP', Selly: 'US', Senoxe: 'US', Shiv: 'US', Skadoodle: 'US',
  SkittleCakes: 'US', Snip3down: 'US', stormen: 'SE', Sweet: 'US',
  Taisheen: 'US', taskmast33r: 'US', Taxi2g: 'US', Unlucky: 'US', Uxako: 'SE',
  Verhulst: 'BE', Viss: 'US', Vooshii: 'US', xaniya: 'US',
  Xynew: 'US', Yuki: 'JP', Zachmazer: 'US', zap: 'US', Zer0: 'US',
};
